int getEditBufferIndex( void );
char getEditBufferChar( int );
void setEditBufferIndex( int );
void autoIndent( void );
void selfInsert( int );
void backspace( void );
void deleteChar( void );
void killWord( void );
void killLine( void );
